// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoy1jsJD00Z9rzvRG1j7Z6cLGuj5rQgWw',
    appId: '1:634639529463:web:d2e039f8c9f799faa0aaf2',
    messagingSenderId: '634639529463',
    projectId: 'come-79956',
    authDomain: 'come-79956.firebaseapp.com',
    storageBucket: 'come-79956.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAghKfvMW9LyMxQPH07ekQiWpYHdFWG_SI',
    appId: '1:634639529463:android:d4e049c4a310002ca0aaf2',
    messagingSenderId: '634639529463',
    projectId: 'come-79956',
    storageBucket: 'come-79956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcxrGHtAGYo8pBVK9oe46T4NC0L01iFqQ',
    appId: '1:634639529463:ios:c249972ea608d782a0aaf2',
    messagingSenderId: '634639529463',
    projectId: 'come-79956',
    storageBucket: 'come-79956.appspot.com',
    iosBundleId: 'com.example.come',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcxrGHtAGYo8pBVK9oe46T4NC0L01iFqQ',
    appId: '1:634639529463:ios:74295260e5efbdcca0aaf2',
    messagingSenderId: '634639529463',
    projectId: 'come-79956',
    storageBucket: 'come-79956.appspot.com',
    iosBundleId: 'com.example.come.RunnerTests',
  );
}
